"""
Script recorder for pystxmcontrol analysis widget.

Provides ScriptRecorder (accumulates actions, renders to Python script) and
the @records decorator for tagging handler methods.
"""

from __future__ import annotations
import datetime
import functools
from typing import Any


# ── Decorator ─────────────────────────────────────────────────────────────────

def records(action_name: str):
    """Decorator that records a handler's return value as a script action.

    The decorated method should return a dict of kwargs when the action
    should be recorded, or None (or nothing) to skip recording (e.g. guard
    clause early returns).  The host object must have a ``_recorder``
    attribute of type ScriptRecorder.

    Usage::

        @records("delete_frame")
        def _on_a2_delete_frame(self):
            if not sv.haveStack:
                return                       # guard — not recorded
            ...
            sv.stack.deleteFrameInPlace(energy)
            return {"energy": float(energy)} # recorded
    """
    def decorator(fn):
        @functools.wraps(fn)
        def wrapper(self, *args, **kwargs):
            result = fn(self, *args, **kwargs)
            if isinstance(result, dict):
                self._recorder.record(action_name, **result)
        return wrapper
    return decorator


# ── Recorder ──────────────────────────────────────────────────────────────────

class ScriptRecorder:
    """Accumulates analysis actions and renders them to a runnable Python script."""

    def __init__(self):
        self._actions: list[tuple[str, dict[str, Any]]] = []
        self.recording: bool = False

    # ── Control ───────────────────────────────────────────────────────────────

    def start(self):
        self._actions.clear()
        self.recording = True

    def stop(self):
        self.recording = False

    def record(self, action: str, **kwargs):
        """Append an action.  No-op when not recording."""
        if self.recording:
            self._actions.append((action, kwargs))

    @property
    def has_actions(self) -> bool:
        return bool(self._actions)

    # ── Export ────────────────────────────────────────────────────────────────

    def export_script(self, filepath: str | None = None) -> str:
        """Render the recorded actions to a Python script string.

        If *filepath* is given the script is also written to disk.
        """
        lines = self._render_header()
        for action, kwargs in self._actions:
            lines.append("")
            lines.extend(self._render_action(action, kwargs))
        script = "\n".join(lines) + "\n"
        if filepath:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(script)
        return script

    # ── Internal ──────────────────────────────────────────────────────────────

    def _render_header(self) -> list[str]:
        date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        return [
            f"# Generated by pystxmcontrol analysis recorder — {date}",
            "from pystxmcontrol.utils.stack import stack as StxmStack",
            "import numpy as np",
        ]

    def _render_action(self, action: str, kwargs: dict) -> list[str]:
        renderer = _RENDERERS.get(action)
        if renderer is None:
            return [f"# Unknown action: {action!r}  kwargs={kwargs!r}"]
        return renderer(kwargs)


# ── Per-action renderers ──────────────────────────────────────────────────────

def _r_load_stack(kw):
    return [f"s = StxmStack({kw.get('filepath', '')!r}, iRegion={kw.get('region', 0)})"]

def _r_delete_frame(kw):
    return [f"s.deleteFrameInPlace({kw.get('energy', 0.0):.4f})"]

def _r_crop_frames(kw):
    r0, r1 = kw.get("row_start", 0), kw.get("row_stop", -1)
    c0, c1 = kw.get("col_start", 0), kw.get("col_stop", -1)
    lines = []
    if kw.get("comment"):
        lines.append(f"# {kw['comment']}")
    lines.append(f"s.cropFrames(slice({r0}, {r1}), slice({c0}, {c1}))")
    return lines

def _r_compute_od(kw):
    return _format_float_array(kw.get("i0_spectrum", []), "_i0") + [
        "s.computeODFromSpectrum(_i0)"
    ]

def _r_compute_od_histogram(kw):
    lo = kw.get("intensity_lo", 0.0)
    hi = kw.get("intensity_hi", 0.0)
    return [f"s.computeODFromHistogramBounds({lo:.6g}, {hi:.6g})"]

def _r_subtract_pre_edge(kw):
    return [f"s.subtractPreEdgeBackground({kw.get('energy_lo', 0.):.4f}, {kw.get('energy_hi', 0.):.4f})"]

def _r_detrend_pre_edge(kw):
    return [f"s.detrendPreEdge({kw.get('energy_lo', 0.):.4f}, {kw.get('energy_hi', 0.):.4f})"]

def _r_align_frames(kw):
    return [
        f"s.alignFrames(mode={kw.get('mode', 'manualtranslation')!r}, "
        f"sobelFilter={kw.get('sobel', False)}, autocrop={kw.get('autocrop', True)})"
    ]

def _r_align_od_frames(kw):
    return [
        f"s.alignODFrames(mode={kw.get('mode', 'manualtranslation')!r}, "
        f"sobelFilter={kw.get('sobel', False)}, autocrop={kw.get('autocrop', True)})"
    ]

def _r_align_frames_custom(kw):
    return [
        f"s.alignFramesCustom("
        f"mode={kw.get('mode', 'manualtranslation')!r}, "
        f"align_method={kw.get('align_method', 'sequential')!r}, "
        f"reference_idx={kw.get('reference_idx', 0)}, "
        f"thresholded={kw.get('thresholded', False)}, "
        f"threshold={kw.get('threshold', 0.0)}, "
        f"sobelFilter={kw.get('sobel', False)}, "
        f"autocrop={kw.get('autocrop', True)})"
    ]

def _r_median_filter(kw):
    return [f"s.medianFilter(size={kw.get('size', 5)}, axis={kw.get('axis', 2)})"]

def _r_despike(kw):
    return [f"s.despike(kernel_size={kw.get('kernel_size', 3)}, n_sigma={kw.get('n_sigma', 5)})"]

def _r_calc_pca(kw):
    return [f"s.calcPCA(nPC={kw.get('n_components', 4)}, nClusters={kw.get('n_clusters', 4)})"]

def _r_calc_nmf(kw):
    return [
        f"s.calcNMF(n_components={kw.get('n_components', 4)}, "
        f"n_clusters={kw.get('n_clusters', 4)}, "
        f"max_iter={kw.get('max_iter', 200)}, "
        f"init={kw.get('init', 'nndsvda')!r})"
    ]


_RENDERERS = {
    "load_stack":            _r_load_stack,
    "delete_frame":          _r_delete_frame,
    "crop_frames":           _r_crop_frames,
    "compute_od":            _r_compute_od,
    "compute_od_histogram":  _r_compute_od_histogram,
    "subtract_pre_edge":   _r_subtract_pre_edge,
    "detrend_pre_edge":    _r_detrend_pre_edge,
    "align_frames":        _r_align_frames,
    "align_od_frames":     _r_align_od_frames,
    "align_frames_custom": _r_align_frames_custom,
    "median_filter":       _r_median_filter,
    "despike":             _r_despike,
    "calc_pca":            _r_calc_pca,
    "calc_nmf":            _r_calc_nmf,
}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _format_float_array(values, name: str, cols: int = 8) -> list[str]:
    """Format a 1-D float sequence as a multi-line numpy array literal."""
    import numpy as np
    arr = list(np.asarray(values, dtype=float))
    if not arr:
        return [f"{name} = np.array([])"]
    chunks = [arr[i:i + cols] for i in range(0, len(arr), cols)]
    inner = ",\n    ".join(", ".join(f"{v:.6g}" for v in chunk) for chunk in chunks)
    return [f"{name} = np.array([", f"    {inner},", f"])"]
